### ISSUE TITLE
Reliance on deprecated uuid library

### ISSUE THREAD

**Issue by eddsalkield** [writeas/web-core#5]
I'm currently working on packaging WriteFreely for Fedora, and I've run into a blocking issue.

Currently, `web-core` depends upon `github.com/nu7hatch/gouuid`.  This library is no longer maintained: the last commit was 7 years ago, it [doesn't implement RFC 4122 correctly](https://github.com/nu7hatch/gouuid/issues/34), and it has suffered [bit rot to the point of the tests no longer passing](https://github.com/nu7hatch/gouuid/issues/33).

It would be easy to change over to a more well-maintained uuid library.  Having done some poking around, it would seem that `github.com/gofrs/uuid` would be a good choice.  It supports RFC 4122 (correctly!), and is actively maintained.

This would really benefit the wider ecosystem as distros wouldn't have to add additional packages for deprecated libraries.

Thanks!

**Comment by thebaer** [comment]
Thanks for taking on this work! Looking forward to seeing the WriteFreely Fedora package.

**Comment by thebaer** [comment]
Fixed by #6.
